# Generated by Django 5.2.3 on 2025-06-23 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duedate',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='due_date', to='task.task'),
        ),
    ]
